config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :forums do
  	collection do
  		get :active
  		get :unanswered
      get :my_posts
  	end
  	resources :forum_comments
  end

  resources :videos do
    resources :video_comments
  end

  resources :programs do
    resources :program_parts, path: "episode"
  end
  
  get 'welcome/index'
  root 'welcome#index'
end

app/models/forum.rb
class Forum < ActiveRecord::Base
	belongs_to :forum_category
	belongs_to :user
	has_many :forum_comments, dependent: :destroy
	validates :title, :content, :forum_category_id, presence: true
	validates :title, length: {in: 5..100}

	scope :active,     ->{ where("forum_comments_count >= ?", 3) }
	scope :unanswered, ->{ where(forum_comments_count: 0) }

  # For Paranoia soft delete
  def user
  	User.unscoped { super }
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :find_forum, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :active, :unanswered]

	def index
		if params[:forum_category].blank?
		  @forums = Forum.all.order("created_at desc").paginate(page: params[:page], per_page: 10)
		else
			@category_id = ForumCategory.find_by(name: params[:forum_category]).id
			@forums = Forum.where(forum_category: @category_id).order("created_at desc").paginate(page: params[:page], per_page: 10)
		end
	end

	def new
		@forum = current_user.forums.build
	end

	def create
		@forum = current_user.forums.build forum_params

		if @forum.save
			redirect_to @forum, notice: "The post was saved successfully!"
		else
			render 'new', notice: "The post was unable to be saved!"
		end
	end

	def show
	end

	def edit
	end

	def update
		if @forum.update forum_params
			redirect_to @forum, notice: "The post was updated successfully!"
		else
			render 'edit'
		end
	end

	def destroy
		@forum.destroy
		redirect_to forums_path
	end

	def active
		@forums = Forum.active.order("created_at desc").paginate(page: params[:page], per_page: 10)
		render action: :index
	end

	def unanswered
		@forums = Forum.unanswered.order("created_at desc").paginate(page: params[:page], per_page: 10)
		render action: :index
	end

	def my_posts
		@forums = current_user.forums.order("created_at desc").paginate(page: params[:page], per_page: 10)
		render action: :index
	end

	private

	def forum_params
		params.require(:forum).permit(:title, :content, :forum_category_id, :slug)
	end

	def find_forum
		@forum = Forum.find(params[:id])
	end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.erb
<%= form_for @forum do |f| %>
  <% if @forum.errors.any? %>
    <h2><%= pluralize(@forum.errors.count, "error") %> prevented this post from saving:</h2>
    <ul>
  	  <% @forum.errors.full_messages.each do |msg| %>
  	    <li><%= msg %></li>
  	  <% end %>
    </ul>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :forum_category_id, "Category" %><br>
    <%= f.collection_select :forum_category_id, ForumCategory.all, :id, :name, { prompt: "Choose a Category" } %>
  </div>

  <div class="field">
    <%= f.label :content%><br>
    <%= f.text_area :content%>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "button button_highlight button_block" %>
  </div>
<% end %>

app/views/forums/edit.html.erb
<div id="banner" class="sign_up_banner">
  <div class="wrapper_skinny">
    <h1>Edit Post</h1>
  </div>
</div>

<div id="form">
  <div class="wrapper_skinny">
    <%= render 'form' %>
  </div>
</div>

app/views/forums/index.html.erb
<div id="banner" class="discussions_banner">
  <div class="wrapper_skinny">
	  <h1>Get help and advice on exercise, nutrition and mobility</h1>
	</div>
</div>

<div id="forum">
	<div class="wrapper_wide cf">
		<div id="forum_posts">
		  <%- if request.fullpath == "/forums?forum_category=Introductions" %>
				<h2 class="category_title">Introductions</h2>
				<p class="category_description">Introduce yourself to the rest of the team.</p>
			<%- elsif request.fullpath == "/forums?forum_category=Lifestyle" %>
				<h2 class="category_title">Lifestyle</h2>
				<p class="category_description">Introduce yourself to the rest of the team.</p>
			<%- elsif request.fullpath == "/forums?forum_category=Exercise" %>
				<h2 class="category_title">Exercise</h2>
				<p class="category_description">Introduce yourself to the rest of the team.</p>
			<%- elsif request.fullpath == "/forums?forum_category=Nutrition" %>
				<h2 class="category_title">Nutrition</h2>
				<p class="category_description">Introduce yourself to the rest of the team.</p>
			<%- elsif request.fullpath == "/forums?forum_category=Mobility" %>
				<h2 class="category_title">Mobility</h2>
				<p class="category_description">Introduce yourself to the rest of the team.</p>
			<%- elsif request.fullpath == "/forums?forum_category=General" %>
				<h2 class="category_title">General</h2>
				<p class="category_description">Introduce yourself to the rest of the team.</p>
			<%- else %>
			  <h2 class="category_title">Everything</h2>
			  <p class="category_description all_category_description">All Posts.</p>
        <nav>
					<ul>
						<%- if request.fullpath == "/forums/active" || request.fullpath == "/forums/unanswered" || request.fullpath == "/forums/my_posts" %>
						  <li><%= link_to "Recent Posts", forums_path %></li>
						<%- else %>
						  <li><%= link_to "Recent Posts", forums_path, class: "active" %></li>
						<% end %>
						<li><%= link_to "Unanswered", unanswered_forums_path, class: "#{active(unanswered_forums_path)}" %></li>
						<li><%= link_to "Active", active_forums_path, class: "#{active(active_forums_path)}" %></li>
						<%- if user_signed_in? %>
						  <li><%= link_to "My Posts", my_posts_forums_path, class: "#{active(my_posts_forums_path)}" %></li>
						<% end %>
					</ul>
				</nav>
			<% end %>

			<%- if @forums.size > 0 %>
	      <%- @forums.each do |forum| %>
	        <div class="forum_post cf">
	          <div class="user_image">
	            <%- if forum.user.avatar.blank? %>
	              <%= image_tag forum.user.avatar.url(:thumb), alt: "Authors Avatar", class: "avatar no_avatar" %>
	            <% else %>
                <%= image_tag forum.user.avatar.url(:thumb), alt: "Authors Avatar", class: "avatar" %>
	            <% end %>
	          </div>
	          <div class="post_content">
	            <h2><%= link_to forum.title, forum %></h2>
	            <p class="post_meta"><span><%= forum.user.username %> </span><%= time_ago_in_words(forum.created_at) %> ago</p>
	            <%= link_to forum.forum_category.name, forums_path(forum_category: forum.forum_category.name), class: "post_category" %>
	          </div>
	          <div class="post_reply_count">
	            <p class="reply_count"><%= forum.forum_comments.count %><span><%= "Reply".pluralize(forum.forum_comments.count) %></span></p>
	          </div>
	        </div>
	      <% end %>

	      <%= will_paginate @forums, previous_label: "Prev", next_label: "Next", inner_window: 1, outer_window: 0 %>
      <%- else %>
	      <p class="no_content">There are no posts in this Category at the moment.</p>
	    <% end %>
		</div>
		<div id="forum_sidebar">
      <%- if user_signed_in? %>
        <%= link_to "New Post", new_forum_path, class: "button button_highlight button_block" %>
      <% end %>
			<a class="category_dropdown">Categories<span class="icon-chevron-down"></span></a>
			<nav>
				<ul>
				  <%- if request.fullpath == "/forums" || request.fullpath == "/forums/active" || request.fullpath == "/forums/unanswered" || request.fullpath == "/forums/my_posts" %>
	          <li><%= link_to "All", forums_path, class: "active" %></li>
	        <%- else %>
	          <li><%= link_to "All", forums_path %></li>
	        <% end %>
					<%- ForumCategory.all.each do |forum_category| %>
				    <li><%= link_to forum_category.name, forums_path(forum_category: forum_category.name), class: "#{active(forums_path(forum_category: forum_category.name))}" %></li>
				  <% end %>
				</ul>
			</nav>
		</div>

	</div>
</div>

app/views/forums/new.html.erb
<div id="banner" class="sign_up_banner">
  <div class="wrapper_skinny">
    <h1>New Post</h1>
  </div>
</div>

<div id="form">
  <div class="wrapper_skinny">
    <%= render 'form' %>
  </div>
</div>

app/views/forums/show.html.erb
<div id="forum_show">
	<div class="forum_wrapper">
    <%= link_to forums_path, class: "back_link" do %>
      <span class="icon-arrow-left2"></span>
      Back to Forum
    <% end %>
		<div class="forum_post cf">
      <div class="user_image">
        <%- if @forum.user.avatar.blank? %>
          <%= image_tag @forum.user.avatar.url(:thumb), alt: "Authors Avatar", class: "avatar no_avatar" %>
        <% else %>
          <%= image_tag @forum.user.avatar.url(:thumb), alt: "Authors Avatar", class: "avatar" %>
        <% end %>
    	</div>
    	<div class="post_content">
        <h2><%= @forum.title %></h2>
      	<p class="post_meta"><span><%= @forum.user.username %> </span><%= time_ago_in_words(@forum.created_at) %> ago</p>
      	<div class="post_text">
          <%= markdown @forum.content %>
      	</div>
        <%= link_to @forum.forum_category.name, forums_path(forum_category: @forum.forum_category.name), class: "post_category" %>
      	
        <%- if @forum.user == current_user || current_user.try(:admin?) %>
          <div class="authorised_links cf">
            <%- if @forum.user == current_user || current_user.try(:admin?) %>
              <%= link_to "Edit", edit_forum_path(@forum), class: "edit_link" %>
            <% end %>
            <%- if current_user.try(:admin?) %>
              <%= link_to "Delete", forum_path(@forum), method: :delete, data: { confirm: "Are you sure?" }, class: "delete_link" %>
            <% end %>
          </div>
        <% end %>
    	</div>
    </div>

    <div class="comments">
    	<h2 class="comment_count"><%= pluralize(@forum.forum_comments.count, "Reply") %></h2>
      <%- if @forum.forum_comments.size > 0 %>
        <%= render @forum.forum_comments %>
      <%- else %>
        <p class="no_content">Be the first to comment.</p>
      <% end %>
    	<h2 class="reply">Reply</h2>
      <%= render "forum_comments/form" %>
    </div>
	</div>
</div>