config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :forums do
  	collection do
  		get :active
  		get :unanswered
      get :my_posts
  	end
  	resources :forum_comments
  end

  resources :videos do
    resources :video_comments
  end

  resources :programs do
    resources :program_parts, path: "episode"
  end
  
  get 'welcome/index'
  root 'welcome#index'
end

app/models/program.rb
class Program < ActiveRecord::Base
	has_many :program_parts, dependent: :destroy
	validates :title, :description, presence: true

  extend FriendlyId
  friendly_id :title, use: :slugged
  
  def should_generate_new_friendly_id?
	  title_changed?
	end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
	before_action :find_program, only: [:show, :edit, :update, :destroy]
	before_action :find_program_part, only: [:show]
  before_action :authenticate_user!, except: [:index]
  before_action :authenticate_admin, only: [:new, :create, :edit, :update, :destroy]

	def index
    @programs = Program.all.order("created_at desc").paginate(page: params[:page], per_page: 10)
	end

	def new
		@program = Program.new
	end

	def create
		@program = Program.new program_params

		if @program.save
  	  redirect_to programs_path, notice: "Program was created successfully!"
  	else
  	  render 'new', notice: "Unable to save program!"
  	end
	end

	def show
	end

	def edit
	end

	def update
		if @program.update program_params
			redirect_to programs_path, notice: "Program was updated successfully!"
		else
			render 'edit', notice: "Program was succesfully updated!"
		end
	end

	def destroy
		@program.destroy
		redirect_to programs_path
	end

	private

	def authenticate_admin
		unless current_user.admin?
			redirect_to programs_path, notice: "You're not supposed to be in there."
		end
	end

	def program_params
		params.require(:program).permit(:title, :description, :slug, :video_id)
	end

	def find_program
		if params[:id].nil?
      @program = current_program
		else
		  @program = Program.friendly.find(params[:id])
		end
	end

	def find_program_part
		@program_parts = ProgramPart.where(program_id: @program).order("created_at asc").paginate(page: params[:page], per_page: 10)
	end
		
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= form_for @program do |f| %>
  <% if @program.errors.any? %>
    <h2><%= pluralize(@program.errors.count, "error") %> prevented this program from saving:</h2>
    <ul>
  	  <% @program.errors.full_messages.each do |msg| %>
  	    <li><%= msg %></li>
  	  <% end %>
    </ul>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :video_id, 'Video URL'%><br>
    <%= f.text_field :video_id %>
  </div>

  <div class="field">
    <%= f.label :description%><br>
    <%= f.text_area :description%>
  </div>

  <div class="actions">
    <%= f.submit class: "button button_highlight button_block" %>
  </div>
<% end %>

app/views/programs/edit.html.erb
<div id="banner" class="sign_up_banner">
  <div class="wrapper_skinny">
    <h1>Edit Program</h1>
  </div>
</div>

<div id="form">
  <div class="wrapper_skinny">
    <%= render 'form' %>
  </div>
</div>

app/views/programs/index.html.erb
<div id="banner" class="programs_banner">
  <%- if current_user.try(:admin?) %>
	  <div class="wrapper_skinny program_admin_headline">
		  <h1>Programs to get you fitter, faster, stronger and leaner</h1>
		  <%= link_to "New Program", new_program_path, class: "button button_highlight" %>
		</div>
  <%- else %>
    <div class="wrapper_skinny">
      <h1>Programs to get you fitter, faster, stronger and leaner</h1>
    </div>
  <% end %>
</div>

<div id="programs">
	<div class="program_wrapper">
	  <%- if @programs.size > 0 %>
      <% @programs.each do |program| %>
        <div class="program">
          <div class="program_info cf">
            <h2><%= program.title %></h2>
	          <p class="program_description"><%= program.description %></p>
		        <%= link_to "View Program", program_path(program), class: "button button_highlight" %>
          </div>
	      </div>
      <% end %>
      <%= will_paginate @programs, previous_label: "Prev", next_label: "Next", inner_window: 1, outer_window: 0 %>
	  <%- else %>
      <p class="no_content">There are no programs at the moment.</p>
	  <% end %>
	</div>
</div>

app/views/programs/new.html.erb
<div id="banner" class="sign_up_banner">
  <div class="wrapper_skinny">
    <h1>New Program</h1>
  </div>
</div>

<div id="form">
  <div class="wrapper_skinny">
    <%= render 'form' %>
  </div>
</div>

app/views/programs/show.html.erb
<div id="program_show">
	<div id="program_show_wrapper" class="cf">
		<div class="wrapper_wide">
			<div class="video">
				<div class="video_inner_wrapper">
	  			<iframe src="<%= @program.video_id %>" width="960" height="540" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
				</div>
			</div>
			<div id="program_content">
				<h1><%= @program.title %></h1>
				<p id="description"><%= @program.description %></p>
				<hr>
				<%= link_to "Back to Programs", programs_path, class: "button button_highlight" %>
	      <%- if current_user.try(:admin?) %>
	        <div class="authorised_links cf">
	          <%= link_to "Edit", edit_program_path(@program), class: "edit_link" %>
	          <%= link_to "Delete", program_path(@program), method: :delete, data: { confirm: "Are you sure you want to delete this program?"}, class: "delete_link" %>
	        </div>
	      <% end %>
			</div>
		</div>
  </div>

  <div id="program_part_wrapper">
    <h2 id="program_part_title">Episodes</h2>
	  <%- if @program_parts.size > 0 %>
	    <% @program_parts.each do |program_part| %>
			  <div class="program_part">
			    <div class="program_part_info cf">
			      <h2><%= program_part.title %></h2>
			      <p class="program_part_description"><%= program_part.description %></p>
			      <p class="program_part_download_open">
					    <%= link_to "Download", program_part.pdf.url, download: program_part.pdf.url, class: "pdf_download" %>
							<%= link_to "Open", program_part.pdf.url, target: "_blank", class: "pdf_open" %>
						</p>
			    </div>
			    <%- if current_user.try(:admin?) %>
			      <div class="authorised_links cf">
			        <%= link_to "Edit", edit_program_program_part_path(program_part.program, program_part), class: "edit_link" %>
			        <%= link_to "Delete", [program_part.program, program_part], method: :delete, data: { confirm: "Are you sure you want to delete this episode?"}, class: "delete_link" %>
			      </div>
			    <% end %>
			  </div>
			<% end %>
			<%= will_paginate @program_parts, previous_label: "Prev", next_label: "Next", inner_window: 1, outer_window: 0 %>
	  <%- else %>
	    <p class="no_content">There are no episodes at the moment.</p>
	  <% end %>
	  <%- if current_user.try(:admin?) %>
		  <div id="new_program_part_button_wrapper">
		    <%= link_to "New Episode", new_program_program_part_path(@program), class: "button button_highlight" %>
		  </div>
		<% end %>
  </div>
</div>