config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :forums do
  	collection do
  		get :active
  		get :unanswered
      get :my_posts
  	end
  	resources :forum_comments
  end

  resources :videos do
    resources :video_comments
  end

  resources :programs do
    resources :program_parts, path: "episode"
  end
  
  get 'welcome/index'
  root 'welcome#index'
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :video_category
  has_many :video_comments, dependent: :destroy
  validates :title, :description, :video_category_id, :image, :video_id, :length, presence: true

	has_attached_file :image, :styles => { :large => "960x540>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  def slug_candidates
    [
      :title,
      [:title, :video_category_id]
    ]
  end

  def should_generate_new_friendly_id?
	  title_changed?
	end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	before_action :find_video, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  before_action :authenticate_admin, only: [:new, :create, :edit, :update, :destroy]

	def index
		if params[:video_category].blank?
			@videos = Video.all.order("created_at desc").paginate(page: params[:page], per_page: 12)
		else
			@category_id = VideoCategory.find_by(name: params[:video_category]).id
			@videos = Video.where(video_category: @category_id).order("created_at desc").paginate(page: params[:page], per_page: 12)
		end
	end

	def new
		@video = Video.new
	end

	def create
		@video = Video.new video_params

		if @video.save
  	  redirect_to @video, notice: "The video was created successfully!"
  	else
  	  render 'new', notice: "The video was unable to be saved!"
  	end
	end

	def show
	end

	def edit
	end

	def update
		if @video.update video_params
			redirect_to @video, notice: "The video was updated successfully!"
		else
			render 'edit'
		end
	end

	def destroy
		@video.destroy
		redirect_to videos_path
	end

	private

	def authenticate_admin
		unless current_user.admin?
			redirect_to videos_path, notice: "You're not supposed to be in there."
		end
	end

	def video_params
		params.require(:video).permit(:title, :length, :description, :video_id, :image, :slug, :video_category_id)
	end

	def find_video
		@video = Video.friendly.find(params[:id])
	end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for @video do |f| %>
  <% if @video.errors.any? %>
    <h2><%= pluralize(@video.errors.count, "error") %> prevented this video from saving:</h2>
    <ul>
  	  <% @video.errors.full_messages.each do |msg| %>
  	    <li><%= msg %></li>
  	  <% end %>
    </ul>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description%><br>
    <%= f.text_area :description%>
  </div>

  <div class="field">
    <%= f.label :video_category_id, "Category" %><br>
    <%= f.collection_select :video_category_id, VideoCategory.all, :id, :name, { prompt: "Choose a Category" } %>
  </div>

  <div class="field">
    <%= f.label :image%><br>
    <%= f.file_field :image%>
  </div>

  <div class="field">
    <%= f.label :video_id, 'Video URL'%><br>
    <%= f.text_field :video_id%>
  </div>

  <div class="field">
    <%= f.label :length%><br>
    <%= f.text_field :length%>
  </div>

  <div class="actions">
    <%= f.submit class: "button button_highlight button_block" %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<div id="banner" class="sign_up_banner">
  <div class="wrapper_skinny">
    <h1>Edit Video</h1>
  </div>
</div>

<div id="form">
  <div class="wrapper_skinny">
    <%= render 'form' %>
  </div>
</div>

app/views/videos/index.html.erb
<div id="banner" class="videos_banner">
  <%- if current_user.try(:admin?) %>
	  <div class="wrapper_skinny video_admin_headline">
		  <h1>A collection of videos covering exercise and mobility</h1>
		  <%= link_to "New Video", new_video_path, class: "button button_highlight" %>
		</div>
  <%- else %>
    <div class="wrapper_skinny">
      <h1>A collection of videos covering exercise and mobility</h1>
    </div>
  <% end %>
</div>

<div id="videos">
	<div class="video_wrapper">
		<nav>
			<ul>
        <%- if request.fullpath == "/videos" %>
          <li><%= link_to "All Videos", videos_path, class: "active" %></li>
        <%- else %>
          <li><%= link_to "All Videos", videos_path %></li>
        <% end %>
			  <%- VideoCategory.all.each do |video_category| %>
			    <li><%= link_to video_category.name, videos_path(video_category: video_category.name), class: "#{active(videos_path(video_category: video_category.name))}" %></li>
			  <% end %>
			</ul>
		</nav>

    <%- if @videos.size > 0 %>
	    <% @videos.each_slice(3) do |videos| %>
	      <div class="video_row cf">
	        <% videos.each do |video| %>
	          <div class="video">
					    <%= link_to video_path(video) do %>
		            <div class="video_thumb" style="background-image: url(<%= video.image(:large) %>);">
				          <div class="tint">
				            <div class="title_wrapper">
				              <h2><%= video.id %>: <%= video.title %></h2>
				              <p class="length"><%= video.length %></p>
				            </div>
				          </div>
				        </div>
				      <% end %>
				      <%= link_to video.video_category.name, videos_path(video_category: video.video_category.name), class: "category" %>
				      <p class="date"><%= video.created_at.strftime('%e %b %Y') %></p>
				      <p class="description"><%= truncate(video.description, length: 110) %></p>
			      </div>
			  	<% end %>
			  </div>
			<% end %>

			<%= will_paginate @videos, previous_label: "Prev", next_label: "Next", inner_window: 1, outer_window: 0 %>
		<%- else %>
      <p class="no_content">There are no videos in this Category at the moment.</p>
    <% end %>

	</div>
</div>

app/views/videos/new.html.erb
<div id="banner" class="sign_up_banner">
  <div class="wrapper_skinny">
    <h1>New Video</h1>
  </div>
</div>

<div id="form">
  <div class="wrapper_skinny">
    <%= render 'form' %>
  </div>
</div>

app/views/videos/show.html.erb
<div id="video_show">
  <div id="video_show_wrapper" class="cf">
  	<div class="wrapper_wide">
  		<div class="video">
  			<div class="video_show_inner_wrapper">
	  			<iframe src="<%= @video.video_id %>" width="960" height="540" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
  			</div>
  		</div>
  		<div id="video_content">
  			<h1><%= @video.id %>: <%= @video.title %></h1>
  			<p id="description"><%= @video.description %></p>
        <%= link_to @video.video_category.name, videos_path(video_category: @video.video_category.name), id: "category" %>
  			<hr>
  			<%= link_to "Back to Videos", videos_path, class: "button button_highlight" %>
        <%- if current_user.try(:admin?) %>
          <div class="authorised_links cf">
            <%= link_to "Edit", edit_video_path(@video), class: "edit_link" %>
            <%= link_to "Delete", video_path(@video), method: :delete, data: { confirm: "Are you sure you want to delete this video?"}, class: "delete_link" %>
          </div>
        <% end %>
  		</div>
  	</div>
	</div>
 	
  <div class="comments">
    <h2 class="comment_count"><%= pluralize(@video.video_comments.count, "Comment") %></h2>
    <%- if @video.video_comments.size > 0 %>
      <%= render @video.video_comments %>
    <%- else %>
      <p class="no_content">Be the first to comment.</p>
    <% end %>
    <h2 class="reply">Comment</h2>
    <%= render "video_comments/form" %>
  </div>
</div>