config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :forums do
  	collection do
  		get :active
  		get :unanswered
      get :my_posts
  	end
  	resources :forum_comments
  end

  resources :videos do
    resources :video_comments
  end

  resources :programs do
    resources :program_parts, path: "episode"
  end
  
  get 'welcome/index'
  root 'welcome#index'
end

app/models/video_comment.rb
class VideoComment < ActiveRecord::Base
  belongs_to :video
  belongs_to :user
  validates :video_comment, presence: true

  # For Paranoia soft delete
  def user
  	User.unscoped { super }
  end
end

app/controllers/video_comments_controller.rb
class VideoCommentsController < ApplicationController
	before_action :find_video
  before_action :authenticate_user!

  def create
		@video_comment = @video.video_comments.create(params[:video_comment].permit(:video_comment))
    @video_comment.user_id = current_user.id if current_user
    @video_comment.save

		if @video_comment.save
			redirect_to video_path(@video, anchor: "video_comment_#{@video_comment.id}")
		else
			redirect_to video_path(@video), alert: "Unable to save your comment"
		end
	end

	def edit
		@video_comment = @video.video_comments.find(params[:id])
	end

	def update
		@video_comment = @video.video_comments.find(params[:id])

		if @video_comment.update(params[:video_comment].permit(:video_comment))
			redirect_to video_path(@video, anchor: "video_comment_#{@video_comment.id}")
		else
			render 'edit'
		end
	end

	def destroy
		@video_comment = @video.video_comments.find(params[:id])
		@video_comment.destroy
		redirect_to video_path(@video)
	end

	private

	def find_video
		@video = Video.find_by_slug(params[:video_id])
	end
end

app/helpers/video_comments_helper.rb
module VideoCommentsHelper
end

app/views/video_comments/_form.html.erb
<%= form_for([@video, @video.video_comments.build]) do |f| %>
  <div class="field">
    <%= f.text_area :video_comment %>
  </div>
  <div class="actions">
    <%= f.submit "Reply", class: "button button_highlight button_block" %>
  </div>
<% end %>

app/views/video_comments/_video_comment.html.erb
<%= div_for(video_comment, class: "cf") do %>
	<div class="user_image">
    <%- if video_comment.user.avatar.blank? %>
      <%= image_tag video_comment.user.avatar.url(:thumb), alt: "Authors Avatar", class: "avatar no_avatar" %>
    <% else %>
      <%= image_tag video_comment.user.avatar.url(:thumb), alt: "Authors Avatar", class: "avatar" %>
    <% end %>
	</div>
  <div class="comment_content">
  	<h2><%= video_comment.user.username %></h2>
  	<p class="comment_meta"><%= time_ago_in_words(@video.created_at) %> ago</p>
  	<div class="comment_text">
  	  <%= markdown video_comment.video_comment %>
  	</div>

    <%- if video_comment.user == current_user || current_user.try(:admin?) %>
      <div class="authorised_links cf">
        <%- if video_comment.user == current_user || current_user.try(:admin?) %>
          <%= link_to "Edit", edit_video_video_comment_path(video_comment.video, video_comment), class: "edit_link" %>
        <% end %>
        <%- if current_user.try(:admin?) %>
          <%= link_to "Delete", [video_comment.video, video_comment], method: :delete, data: { confirm: "Are you sure?" }, class: "delete_link" %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/video_comments/edit.html.erb
<div id="banner" class="sign_up_banner">
  <div class="wrapper_skinny">
    <h1>Edit Comment</h1>
  </div>
</div>

<div id="form">
  <div class="wrapper_skinny">
    <%= form_for([@video, @video_comment]) do |f| %>
		  <div class="field">
		    <%= f.text_area :video_comment %>
		  </div>
		  <div class="actions">
		    <%= f.submit "Update", class: "button button_highlight button_block" %>
		  </div>
		<% end %>
  </div>
</div>